name: Bug Report
description: File a bug report to help us improve StarForgeFrontier
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Tell us how to reproduce this behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Game Component
      description: Which part of the game is affected?
      options:
        - Multiplayer/Networking
        - Ship Building System
        - Resource/Economy System
        - Game Physics
        - User Interface
        - Server Performance
        - Client Rendering
        - WebSocket Connection
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Game breaking, prevents play)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue, cosmetic)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
      value: |
        - OS: [e.g. macOS, Windows, Linux]
        - Browser: [e.g. Chrome, Firefox, Safari]
        - Browser Version: [e.g. 91.0.4472.124]
        - Game Version: [if known]
        - Node.js Version: [if running locally]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs/Errors
      description: If applicable, add browser console logs or server error messages
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I have provided all requested information
          required: true
        - label: I can reproduce this issue consistently
          required: true