blank_issues_enabled: false
contact_links:
  - name: Discussion Forum
    url: https://github.com/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/wiki
    about: Read the project documentation and guides